dependencies:
- name: activemq
  version: ^1.0.0
  repository: https://kubernetes-charts.alfresco.com/stable
- name: common
  repository: https://github.com/ogaryo/activiti-cloud-charts/tree/master/
  version: 1.1.5