dependencies:
- name: infrastructure
  repository: https://github.com/ogaryo/activiti-cloud-charts/tree/master/
  version: 1.1.9
- name: application
  repository: https://github.com/ogaryo/activiti-cloud-charts/tree/master/
  version: 1.1.12
- name: activiti-cloud-modeling
  repository: https://github.com/ogaryo/activiti-cloud-charts/tree/master/
  version: 1.1.10
  condition: activiti-cloud-modeling.enabled,modeling.enabled
