dependencies:
- name: keycloak
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.1.0
  condition: keycloak.enabled
- name: common
  repository: https://github.com/ogaryo/activiti-cloud-charts/
  version: 1.1.5
